SELECT * FROM P4ITEM_CATEGORY ;
SELECT * FROM P4COUPON;
SELECT * FROM P4GRADE;
SELECT * FROM P4ADMIN;
SELECT * FROM P4MEMBER;
SELECT * FROM P4POINT;
SELECT * FROM P4MEMCOUPON;
SELECT * FROM P4CAROUSEL;
SELECT * FROM P4RECOMMEND;
SELECT * FROM P4ALARM;
SELECT * FROM P4EMONEY;
SELECT * FROM P4FAQ;
SELECT * FROM P4FAVOR_ITEM;
SELECT * FROM P4FOLLOW;
SELECT * FROM P4ITEM_QUERY;
SELECT * FROM P4MANAGE_INCOME;
SELECT * FROM P4NOTICE;
SELECT * FROM P4QNA;
SELECT * FROM P4RENT_ITEM;
SELECT * FROM P4RENTAL;
SELECT * FROM P4REPORT;
SELECT * FROM P4REQ_ITEM;


/* 캐러셀 배너 */

SELECT CAROU_IMG, CAROU_LINK
FROM P4CAROUSEL
ORDER BY CAROU_ORDER;

/* ZENTAL 추천 렌탈 상품 */

SELECT pri.RENT_ITEM_IMG, pri.RENT_ITEM_TITLE, pri.RENT_ITEM_PRICE, pri.RENT_ITEM_PRICE_PER
FROM P4RECOMMEND pr, P4RENT_ITEM pri
ORDER BY pr.RECOMM_ORDER;

/* 카테고리별 렌탈 상품 IT */

SELECT RENT_ITEM_IMG, RENT_ITEM_TITLE, RENT_ITEM_PRICE, RENT_ITEM_PRICE_PER
FROM P4RENT_ITEM
WHERE CATE_NAME = 'IT' AND ROWNUM <= 5
ORDER BY RENT_ITEM_SDATE;

/* 카테고리별 렌탈 상품 가전 */

SELECT RENT_ITEM_IMG, RENT_ITEM_TITLE, RENT_ITEM_PRICE, RENT_ITEM_PRICE_PER
FROM P4RENT_ITEM
WHERE CATE_NAME = '가전' AND ROWNUM <= 5
ORDER BY RENT_ITEM_SDATE;

/* 카테고리별 렌탈 상품 가구 */

SELECT RENT_ITEM_IMG, RENT_ITEM_TITLE, RENT_ITEM_PRICE, RENT_ITEM_PRICE_PER
FROM P4RENT_ITEM
WHERE CATE_NAME = '가구' AND ROWNUM <= 5
ORDER BY RENT_ITEM_SDATE;

/* 카테고리별 렌탈 상품 스포츠 */

SELECT RENT_ITEM_IMG, RENT_ITEM_TITLE, RENT_ITEM_PRICE, RENT_ITEM_PRICE_PER
FROM P4RENT_ITEM
WHERE CATE_NAME = '스포츠' AND ROWNUM <= 5
ORDER BY RENT_ITEM_SDATE;

/* 카테고리별 렌탈 상품 레저 */

SELECT RENT_ITEM_IMG, RENT_ITEM_TITLE, RENT_ITEM_PRICE, RENT_ITEM_PRICE_PER
FROM P4RENT_ITEM
WHERE CATE_NAME = '레저' AND ROWNUM <= 5
ORDER BY RENT_ITEM_SDATE;
