SELECT * FROM P4ITEM_CATEGORY ;
SELECT * FROM P4COUPON;
SELECT * FROM P4GRADE;
SELECT * FROM P4ADMIN;
SELECT * FROM P4MEMBER;
SELECT * FROM P4POINT;
SELECT * FROM P4MEMCOUPON;
SELECT * FROM P4CAROUSEL;
SELECT * FROM P4RECOMMEND;
SELECT * FROM P4ALARM;
SELECT * FROM P4EMONEY;
SELECT * FROM P4FAQ;
SELECT * FROM P4FAVOR_ITEM;
SELECT * FROM P4FOLLOW;
SELECT * FROM P4ITEM_QUERY;
SELECT * FROM P4MANAGE_INCOME;
SELECT * FROM P4NOTICE;
SELECT * FROM P4QNA;
SELECT * FROM P4RENT_ITEM;
SELECT * FROM P4RENTAL;
SELECT * FROM P4REPORT;
SELECT * FROM P4REQ_ITEM;



SELECT * FROM P4RECOMMEND;

/* 추천 상품 리스트 */

SELECT pr.RECOMM_DATE, pr.RECOMM_ORDER, pri.MEM_ID, pri.RENT_ITEM_TITLE
FROM P4RECOMMEND pr, P4RENT_ITEM pri
WHERE pr.RENT_ITEM_CODE = pri.RENT_ITEM_CODE
ORDER BY pr.RENT_ITEM_CODE ;

/* 추천 상품 리스트 제외 */

DELETE
FROM P4RECOMMEND
WHERE RENT_ITEM_CODE = 21000000;

/* 추천 상품 리스트 순서 변경 */

UPDATE P4RECOMMEND
SET RECOMM_ORDER = 3
WHERE RENT_ITEM_CODE = 21000006;

/* 추천 상품 등록 */

INSERT INTO P4RECOMMEND VALUES (21000007, sysdate, 4);