SELECT * FROM P4ITEM_CATEGORY ;
SELECT * FROM P4COUPON;
SELECT * FROM P4GRADE;
SELECT * FROM P4ADMIN;
SELECT * FROM P4MEMBER;
SELECT * FROM P4POINT;
SELECT * FROM P4MEMCOUPON;
SELECT * FROM P4CAROUSEL;
SELECT * FROM P4RECOMMEND;
SELECT * FROM P4ALARM;
SELECT * FROM P4EMONEY;
SELECT * FROM P4FAQ;
SELECT * FROM P4FAVOR_ITEM;
SELECT * FROM P4FOLLOW;
SELECT * FROM P4ITEM_QUERY;
SELECT * FROM P4MANAGE_INCOME;
SELECT * FROM P4NOTICE;
SELECT * FROM P4QNA;
SELECT * FROM P4RENT_ITEM;
SELECT * FROM P4RENTAL;
SELECT * FROM P4REPORT;
SELECT * FROM P4REQ_ITEM;

SELECT pr.RENTAL_CURR
FROM P4ALARM pa, P4RENTAL pr
WHERE pa.MEM_ID = 'userezenht' AND pa.ALARM_CHK = 0 AND pa.RENTAL_CODE = pr.RENTAL_CODE;

SELECT pr2.REPORT_DATE
FROM P4ALARM pa, P4REPORT pr2
WHERE pa.MEM_ID = 'userezenht' AND pa.ALARM_CHK = 0 AND pa.REPORT_CODE = pr2.REPORT_CODE;

SELECT pq.QNA_TITLE
FROM P4ALARM pa, P4QNA pq
WHERE pa.MEM_ID = 'userezenht' AND pa.ALARM_CHK = 0 AND pa.QNA_CODE = pq.QNA_CODE;

SELECT piq.QUERY_ANSWER
FROM P4ALARM pa, P4ITEM_QUERY piq
WHERE pa.MEM_ID = 'userezenht' AND pa.ALARM_CHK = 0 AND pa.QUERY_CODE = piq.QUERY_CODE;

SELECT pri.REQ_TITLE
FROM P4ALARM pa, P4REQ_ITEM pri
WHERE pa.MEM_ID = 'userezenht' AND pa.ALARM_CHK = 0 AND pa.REQ_CODE = pri.REQ_CODE;

